-- GENERATED by packages/core/scripts/gen-priority-parity.ts from packages/core/src/priority/fixtures.ts.
-- Do not edit; run `pnpm --filter @studypulse/core priority:parity` after changing the formula.
begin;
select plan(13);

select ok(abs(public.task_priority(30, '2027-03-06T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 300, 'todo', 120) - 67.857) < 0.002, 'parity: 30% midterm in 5 days = 67.857');
select ok(abs(public.task_priority(2, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'todo', 120) - 39.915) < 0.002, 'parity: 2% quiz tomorrow = 39.915');
select ok(abs(public.task_priority(2, '2027-03-01T18:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'todo', 120) - 59.201) < 0.002, 'parity: 2% quiz in 3 hours = 59.201');
select ok(abs(public.task_priority(30, '2027-03-22T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 300, 'todo', 120) - 57.308) < 0.002, 'parity: 30% final in 3 weeks = 57.308');
select ok(abs(public.task_priority(10, '2027-03-05T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 600, 'todo', 120) - 76.754) < 0.002, 'parity: heavy work no longer fits = 76.754');
select ok(abs(public.task_priority(10, '2027-03-04T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'in_progress', 120) - 49.073) < 0.002, 'parity: in progress = 49.073');
select ok(abs(public.task_priority(40, '2027-02-27T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'in_progress', 120) - 100.000) < 0.002, 'parity: in progress capped = 100.000');
select ok(abs(public.task_priority(5, '2027-02-28T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 67.454) < 0.002, 'parity: overdue = 67.454');
select ok(abs(public.task_priority(5, null, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 24.704) < 0.002, 'parity: undated = 24.704');
select ok(abs(public.task_priority(30, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 0, 'done', 120) - 0.000) < 0.002, 'parity: done = 0.000');
select ok(abs(public.task_priority(30, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 0, 'skipped', 120) - 0.000) < 0.002, 'parity: skipped = 0.000');
select ok(abs(public.task_priority(15, '2027-03-07T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 240, 'todo', 30) - 83.891) < 0.002, 'parity: low daily capacity = 83.891');
select ok(abs(public.task_priority(0, '2027-03-03T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 45, 'todo', 90) - 18.000) < 0.002, 'parity: zero share = 18.000');

select * from finish();
rollback;
