// Dependency license check (launch safety S27).
//
//   node scripts/license-check.mjs           # fail on a license that isn't allowed
//   node scripts/license-check.mjs --write   # also regenerate the table in docs/licenses.md
//
// Reads every installed package's license from `pnpm licenses list --json -r` (all
// workspaces, dev dependencies included). Permissive licenses pass. Anything else passes
// only when the package is in REVIEWED below with the reason it's acceptable; GPL, AGPL,
// SSPL, unknown, or a new copyleft package fails the run and names it.
import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const root = fileURLToPath(new URL("..", import.meta.url));
const doc = fileURLToPath(new URL("../docs/licenses.md", import.meta.url));

/** Permissive licenses: fine to ship, attribution via the package's own notice. */
export const PERMISSIVE = new Set([
  "MIT",
  "MIT-0",
  "ISC",
  "Apache-2.0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "0BSD",
  "Unlicense",
  "CC0-1.0",
  "BlueOak-1.0.0",
  "Python-2.0",
  "CC-BY-4.0",
  "MIT AND Apache-2.0",
  "(MIT OR Apache-2.0)",
  "(MIT OR CC0-1.0)",
]);

/**
 * Non-permissive licenses we reviewed, by package name (a prefix matches the
 * platform-specific builds, e.g. lightningcss-linux-x64-gnu). A new package under one of
 * these licenses still fails until someone reviews it and adds it here.
 */
export const REVIEWED = [
  {
    prefix: "@img/sharp-libvips",
    license: "LGPL-3.0-or-later",
    reason:
      "libvips, used by Next's image optimizer on the server; dynamically linked and unmodified, so LGPL is satisfied. Never shipped to browsers or phones.",
  },
  {
    prefix: "node-forge",
    license: "(BSD-3-Clause OR GPL-2.0)",
    reason: "Dual-licensed; we use it under BSD-3-Clause. Build tooling (Expo dev server).",
  },
  {
    prefix: "@sentry/cli",
    license: "FSL-1.1-MIT",
    reason:
      "Build-time tool that uploads source maps. FSL only restricts offering a competing service; it isn't shipped in the app.",
  },
  {
    prefix: "axe-core",
    license: "MPL-2.0",
    reason: "Dev-only accessibility audit. MPL is file-level copyleft; we don't modify it.",
  },
  {
    prefix: "lightningcss",
    license: "MPL-2.0",
    reason: "Build-time CSS compiler; unmodified, not shipped.",
  },
];

/** Never allowed, even by review: would force releasing StudyPulse's own source. */
const FORBIDDEN = /\b(A?GPL|SSPL|EUPL|OSL|CPAL|Commons-Clause|BUSL)\b/i;

export function classify(name, license) {
  const reviewed = REVIEWED.find((r) => name.startsWith(r.prefix) && r.license === license);
  if (reviewed) return { ok: true, reviewed };
  if (PERMISSIVE.has(license)) return { ok: true };
  if (FORBIDDEN.test(license)) return { ok: false, why: "copyleft or source-available" };
  return { ok: false, why: "not on the permissive list and not reviewed" };
}

function listLicenses() {
  const out = execFileSync("pnpm", ["licenses", "list", "--json", "-r"], {
    cwd: root,
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  /** @type {Record<string, {name: string, versions: string[]}[]>} */
  const byLicense = JSON.parse(out);
  return Object.entries(byLicense).flatMap(([license, pkgs]) =>
    pkgs.map((p) => ({ name: p.name, versions: p.versions, license })),
  );
}

function renderTable(pkgs) {
  const counts = new Map();
  for (const p of pkgs) counts.set(p.license, (counts.get(p.license) ?? 0) + 1);
  const rows = [...counts]
    .sort((a, b) => b[1] - a[1] || a[0].localeCompare(b[0]))
    .map(([license, n]) => `| ${license} | ${n} |`);
  const reviewed = pkgs
    .map((p) => ({ p, c: classify(p.name, p.license) }))
    .filter(({ c }) => c.reviewed)
    .sort((a, b) => a.p.name.localeCompare(b.p.name))
    .map(({ p, c }) => `| ${p.name} | ${p.license} | ${c.reviewed.reason} |`);
  return [
    "<!-- license-table:start (generated by `pnpm licenses:check --write`; don't edit) -->",
    "",
    `${pkgs.length} packages across all workspaces, dev dependencies included.`,
    "",
    "| License | Packages |",
    "| ------- | -------- |",
    ...rows,
    "",
    "Reviewed non-permissive packages:",
    "",
    "| Package | License | Why it's acceptable |",
    "| ------- | ------- | ------------------- |",
    ...reviewed,
    "",
    "<!-- license-table:end -->",
  ].join("\n");
}

function main() {
  const pkgs = listLicenses();
  const bad = pkgs.map((p) => ({ p, c: classify(p.name, p.license) })).filter(({ c }) => !c.ok);

  if (process.argv.includes("--write")) {
    const text = readFileSync(doc, "utf8");
    const next = text.replace(
      /<!-- license-table:start[\s\S]*?<!-- license-table:end -->/,
      renderTable(pkgs),
    );
    writeFileSync(doc, next);
    execFileSync("pnpm", ["exec", "prettier", "--write", doc], { cwd: root, stdio: "ignore" });
    console.log(`Updated ${doc}`);
  }

  if (bad.length > 0) {
    console.error("License check failed:");
    for (const { p, c } of bad) {
      console.error(`  ${p.name}@${p.versions.join(",")}: ${p.license} (${c.why})`);
    }
    console.error(
      "Replace the package, or review it and add it to REVIEWED in scripts/license-check.mjs.",
    );
    process.exit(1);
  }
  console.log(`License check passed: ${pkgs.length} packages, none GPL, AGPL, or unreviewed.`);
}

if (process.argv[1] === fileURLToPath(import.meta.url)) main();
