// Database types. `database.types.ts` will be generated by the Supabase CLI
// once migrations exist; until then it is an empty placeholder schema.
export type { Database, Json } from "./database.types";
