-- Study session start/stop endpoints (RPCs). Idempotent via client-generated ids;
-- overlapping sessions are impossible (exclusion constraint), including a second
-- running session.

create extension if not exists btree_gist with schema extensions;

-- A running session occupies [started_at, infinity).
alter table public.study_sessions
  add constraint study_sessions_no_overlap
  exclude using gist (
    user_id with =,
    tstzrange(started_at, coalesce(ended_at, 'infinity'::timestamptz), '[)') with &&
  );

-- Start a session. p_id is generated by the client and reused on retries, so a retry
-- after a lost response returns the same session instead of failing or duplicating.
-- p_started_at lets an offline client report when it really started (within limits).
create or replace function public.start_study_session(
  p_id uuid,
  p_course_id uuid,
  p_assignment_id uuid default null,
  p_started_at timestamptz default null
)
returns public.study_sessions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_user_id uuid := (select auth.uid());
  v_started timestamptz := coalesce(p_started_at, now());
  v_session public.study_sessions;
begin
  if v_user_id is null then
    raise exception 'not authenticated' using errcode = '42501';
  end if;

  select * into v_session from public.study_sessions where id = p_id;
  if found then
    if v_session.user_id <> v_user_id then
      raise exception 'session id already used' using errcode = '23505';
    end if;
    if v_session.course_id is distinct from coalesce(
         (select a.course_id from public.assignments a where a.id = p_assignment_id), p_course_id)
       or v_session.assignment_id is distinct from p_assignment_id then
      raise exception 'session % already exists with different details', p_id using errcode = '23505';
    end if;
    return v_session; -- idempotent retry
  end if;

  if v_started > now() + interval '5 minutes' then
    raise exception 'started_at is in the future' using errcode = '22023';
  end if;
  if v_started < now() - interval '24 hours' then
    raise exception 'started_at is more than 24 hours ago' using errcode = '22023';
  end if;

  begin
    insert into public.study_sessions (id, user_id, course_id, assignment_id, started_at, source)
    values (p_id, v_user_id, p_course_id, p_assignment_id, v_started, 'timer')
    returning * into v_session;
  exception when exclusion_violation then
    raise exception 'another study session overlaps this one; stop it first'
      using errcode = '23P01', hint = 'session_overlap';
  end;

  -- Working on it now: a to-do assignment becomes in progress.
  if p_assignment_id is not null then
    update public.assignments set status = 'in_progress' where id = p_assignment_id and status = 'todo';
  end if;

  return v_session;
end;
$$;

-- Stop a session. Idempotent: stopping an already-stopped session returns it unchanged.
create or replace function public.stop_study_session(p_id uuid, p_ended_at timestamptz default null)
returns public.study_sessions
language plpgsql
security invoker
set search_path = ''
as $$
declare
  v_session public.study_sessions;
  v_ended timestamptz := coalesce(p_ended_at, now());
begin
  if (select auth.uid()) is null then
    raise exception 'not authenticated' using errcode = '42501';
  end if;

  select * into v_session from public.study_sessions where id = p_id for update;
  if not found then
    raise exception 'study session % not found', p_id using errcode = 'P0002';
  end if;
  if v_session.ended_at is not null then
    return v_session; -- idempotent retry
  end if;

  if v_ended > now() + interval '5 minutes' then
    raise exception 'ended_at is in the future' using errcode = '22023';
  end if;
  if v_ended <= v_session.started_at then
    raise exception 'ended_at must be after started_at' using errcode = '22023';
  end if;
  -- Forgotten timers are capped rather than rejected.
  v_ended := least(v_ended, v_session.started_at + interval '12 hours');

  begin
    update public.study_sessions set ended_at = v_ended where id = p_id returning * into v_session;
  exception when exclusion_violation then
    raise exception 'this session would overlap another one' using errcode = '23P01', hint = 'session_overlap';
  end;
  return v_session;
end;
$$;

revoke execute on function public.start_study_session(uuid, uuid, uuid, timestamptz) from public, anon;
revoke execute on function public.stop_study_session(uuid, timestamptz) from public, anon;
grant execute on function public.start_study_session(uuid, uuid, uuid, timestamptz) to authenticated;
grant execute on function public.stop_study_session(uuid, timestamptz) to authenticated;
