import { currentGrade } from "./current.ts";
import { GRADE_FIXTURES } from "./fixtures.ts";

const uuid = (fixture: number, kind: string, n: number) =>
  `${kind}${String(fixture).padStart(2, "0")}0000-0000-4000-8000-${String(n).padStart(12, "0")}`;

/** The generated pgTAP test asserting SQL course_current_grade() == TS currentGrade(). */
export function renderGradeParitySql(): string {
  const lines = [
    "-- GENERATED by packages/core/scripts/gen-grade-parity.ts from packages/core/src/grades/fixtures.ts.",
    "-- Do not edit; run `pnpm --filter @studypulse/core grades:parity` after changing grade math.",
    "begin;",
    "delete from auth.users;",
    `select plan(${String(GRADE_FIXTURES.length)});`,
    "select tests.create_user('parity@example.com') as uid \\gset",
    "",
  ];
  GRADE_FIXTURES.forEach((f, fi) => {
    const course = uuid(fi, "c0", 0);
    lines.push(
      `insert into public.courses (id, user_id, name) values ('${course}', :'uid', 'fixture ${String(fi)}');`,
    );
    const catIds = new Map<string, string>();
    f.input.categories.forEach((c, ci) => {
      const id = uuid(fi, "ca", ci + 1);
      catIds.set(c.id, id);
      lines.push(
        `insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('${id}', '${course}', '${c.name}', ${String(c.weight)}, ${String(c.dropLowest ?? 0)});`,
      );
    });
    f.input.assignments.forEach((a, ai) => {
      const cat = a.categoryId ? `'${catIds.get(a.categoryId) ?? ""}'` : "null";
      const num = (x: number | null) => (x === null ? "null" : String(x));
      lines.push(
        `insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('${course}', ${cat}, 'a${String(ai)}', ${num(a.pointsEarned)}, ${num(a.pointsPossible)});`,
      );
    });
    const expected = currentGrade(f.input).percent;
    lines.push(
      expected === null
        ? `select is(public.course_current_grade('${course}'), null, 'parity: ${f.name} = null');`
        : `select ok(abs(public.course_current_grade('${course}') - ${expected.toFixed(6)}) < 0.0001, 'parity: ${f.name} = ${expected.toFixed(4)}');`,
      "",
    );
  });
  lines.push("select * from finish();", "rollback;", "");
  return lines.join("\n");
}
