-- GENERATED by packages/core/scripts/gen-priority-parity.ts from packages/core/src/priority/fixtures.ts.
-- Do not edit; run `pnpm --filter @studypulse/core priority:parity` after changing the formula.
begin;
select plan(30);

select ok(abs(public.task_priority(30, '2027-03-06T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 300, 'todo', 120) - 64.286) < 0.002, 'parity: 30% midterm in 5 days = 64.286');
select ok(abs(public.task_priority(2, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'todo', 120) - 41.932) < 0.002, 'parity: 2% quiz tomorrow = 41.932');
select ok(abs(public.task_priority(2, '2027-03-01T18:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'todo', 120) - 57.361) < 0.002, 'parity: 2% quiz in 3 hours = 57.361');
select ok(abs(public.task_priority(30, '2027-03-22T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 300, 'todo', 120) - 55.846) < 0.002, 'parity: 30% final in 3 weeks = 55.846');
select ok(abs(public.task_priority(10, '2027-03-05T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 600, 'todo', 120) - 71.403) < 0.002, 'parity: heavy work no longer fits = 71.403');
select ok(abs(public.task_priority(10, '2027-03-04T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'in_progress', 120) - 49.258) < 0.002, 'parity: in progress = 49.258');
select ok(abs(public.task_priority(40, '2027-02-27T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'in_progress', 120) - 100.000) < 0.002, 'parity: in progress capped = 100.000');
select ok(abs(public.task_priority(5, '2027-02-28T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 96.745) < 0.002, 'parity: overdue = 96.745');
select ok(abs(public.task_priority(5, null, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 2.470) < 0.002, 'parity: undated = 2.470');
select ok(abs(public.task_priority(30, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 0, 'done', 120) - 0.000) < 0.002, 'parity: done = 0.000');
select ok(abs(public.task_priority(30, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 0, 'skipped', 120) - 0.000) < 0.002, 'parity: skipped = 0.000');
select ok(abs(public.task_priority(15, '2027-03-07T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 240, 'todo', 30) - 77.113) < 0.002, 'parity: low daily capacity = 77.113');
select ok(abs(public.task_priority(0, '2027-03-03T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 45, 'todo', 90) - 1.800) < 0.002, 'parity: zero share = 1.800');
select ok(abs(public.task_priority(30, '2027-03-01T12:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 120, 'todo', 120) - 100.000) < 0.002, 'parity: overdue 3 hours, 30% = 100.000');
select ok(abs(public.task_priority(0, '2027-02-28T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 94.500) < 0.002, 'parity: overdue 1 day, no category (0%) = 94.500');
select ok(abs(public.task_priority(2, '2027-02-23T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'in_progress', 120) - 96.512) < 0.002, 'parity: overdue 6 days, 2%, in progress = 96.512');
select ok(abs(public.task_priority(10, '2027-01-30T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 90, 'todo', 120) - 97.675) < 0.002, 'parity: overdue 30 days, 10% = 97.675');
select ok(abs(public.task_priority(20, '2027-02-27T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 0, 'todo', 120) - 98.991) < 0.002, 'parity: overdue, nothing left to do = 98.991');
select ok(abs(public.task_priority(30, '2027-02-28T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 0, 'done', 120) - 0.000) < 0.002, 'parity: overdue but done = 0.000');
select ok(abs(public.task_priority(30, '2027-02-28T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'skipped', 120) - 0.000) < 0.002, 'parity: overdue but skipped = 0.000');
select ok(abs(public.task_priority(30, null, '2027-03-01T15:00:00Z'::timestamptz, 300, 'todo', 120) - 5.725) < 0.002, 'parity: undated, 30% share = 5.725');
select ok(abs(public.task_priority(0, null, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 0.225) < 0.002, 'parity: undated, no share = 0.225');
select ok(abs(public.task_priority(10, null, '2027-03-01T15:00:00Z'::timestamptz, 60, 'in_progress', 120) - 3.740) < 0.002, 'parity: undated, in progress = 3.740');
select ok(abs(public.task_priority(10, null, '2027-03-01T15:00:00Z'::timestamptz, 60, 'done', 120) - 0.000) < 0.002, 'parity: undated but done = 0.000');
select ok(abs(public.task_priority(0, '2027-03-02T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 45, 'todo', 120) - 2.769) < 0.002, 'parity: no category, due tomorrow = 2.769');
select ok(abs(public.task_priority(0, '2027-03-01T18:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'in_progress', 120) - 4.950) < 0.002, 'parity: no category, due in 3 hours, in progress = 4.950');
select ok(abs(public.task_priority(10, '2027-03-04T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 60, 'todo', 120) - 45.689) < 0.002, 'parity: 10% in 3 days, not started = 45.689');
select ok(abs(public.task_priority(5, '2027-03-01T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 30, 'todo', 120) - 63.963) < 0.002, 'parity: due exactly now = 63.963');
select ok(abs(public.task_priority(100, '2027-03-15T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 600, 'todo', 120) - 57.600) < 0.002, 'parity: 100% share in 2 weeks = 57.600');
select ok(abs(public.task_priority(15, '2027-03-07T15:00:00.000Z'::timestamptz, '2027-03-01T15:00:00Z'::timestamptz, 240, 'todo', 0) - 48.313) < 0.002, 'parity: zero daily capacity uses the default = 48.313');

select * from finish();
rollback;
