-- GENERATED by packages/core/scripts/gen-grade-parity.ts from packages/core/src/grades/fixtures.ts.
-- Do not edit; run `pnpm --filter @studypulse/core grades:parity` after changing grade math.
begin;
delete from auth.users;
select plan(6);
select tests.create_user('parity@example.com') as uid \gset
-- Pro, so the free plan's 3-course limit doesn't cap the number of fixtures.
insert into public.subscriptions (user_id, provider, provider_subscription_id, status) values (:'uid', 'stripe', 'sub_parity', 'active');

insert into public.courses (id, user_id, name) values ('c0000000-0000-4000-8000-000000000000', :'uid', 'fixture 0');
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca000000-0000-4000-8000-000000000001', 'c0000000-0000-4000-8000-000000000000', 'Exams', 50, 0);
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca000000-0000-4000-8000-000000000002', 'c0000000-0000-4000-8000-000000000000', 'Homework', 30, 0);
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca000000-0000-4000-8000-000000000003', 'c0000000-0000-4000-8000-000000000000', 'Quizzes', 20, 0);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0000000-0000-4000-8000-000000000000', 'ca000000-0000-4000-8000-000000000001', 'a0', 80, 100);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0000000-0000-4000-8000-000000000000', 'ca000000-0000-4000-8000-000000000002', 'a1', 10, 10);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0000000-0000-4000-8000-000000000000', 'ca000000-0000-4000-8000-000000000002', 'a2', 5, 10);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0000000-0000-4000-8000-000000000000', 'ca000000-0000-4000-8000-000000000003', 'a3', null, 10);
select ok(abs(public.course_current_grade('c0000000-0000-4000-8000-000000000000') - 78.125000) < 0.0001, 'parity: weighted with an empty category = 78.1250');

insert into public.courses (id, user_id, name) values ('c0010000-0000-4000-8000-000000000000', :'uid', 'fixture 1');
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca010000-0000-4000-8000-000000000001', 'c0010000-0000-4000-8000-000000000000', 'Quizzes', 40, 2);
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca010000-0000-4000-8000-000000000002', 'c0010000-0000-4000-8000-000000000000', 'Exams', 60, 0);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0010000-0000-4000-8000-000000000000', 'ca010000-0000-4000-8000-000000000001', 'a0', 5, 10);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0010000-0000-4000-8000-000000000000', 'ca010000-0000-4000-8000-000000000001', 'a1', 40, 100);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0010000-0000-4000-8000-000000000000', 'ca010000-0000-4000-8000-000000000001', 'a2', 40, 50);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0010000-0000-4000-8000-000000000000', 'ca010000-0000-4000-8000-000000000001', 'a3', 9, 10);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0010000-0000-4000-8000-000000000000', 'ca010000-0000-4000-8000-000000000001', 'a4', 2, 20);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0010000-0000-4000-8000-000000000000', 'ca010000-0000-4000-8000-000000000002', 'a5', 70, 100);
select ok(abs(public.course_current_grade('c0010000-0000-4000-8000-000000000000') - 72.857143) < 0.0001, 'parity: drop lowest two of five quizzes = 72.8571');

insert into public.courses (id, user_id, name) values ('c0020000-0000-4000-8000-000000000000', :'uid', 'fixture 2');
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca020000-0000-4000-8000-000000000001', 'c0020000-0000-4000-8000-000000000000', 'Homework', 100, 0);
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca020000-0000-4000-8000-000000000002', 'c0020000-0000-4000-8000-000000000000', 'Bonus', 0, 0);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0020000-0000-4000-8000-000000000000', 'ca020000-0000-4000-8000-000000000001', 'a0', 11, 10);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0020000-0000-4000-8000-000000000000', 'ca020000-0000-4000-8000-000000000001', 'a1', 8, 10);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0020000-0000-4000-8000-000000000000', 'ca020000-0000-4000-8000-000000000002', 'a2', 5, 5);
select ok(abs(public.course_current_grade('c0020000-0000-4000-8000-000000000000') - 95.000000) < 0.0001, 'parity: extra credit and zero-weight bonus = 95.0000');

insert into public.courses (id, user_id, name) values ('c0030000-0000-4000-8000-000000000000', :'uid', 'fixture 3');
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0030000-0000-4000-8000-000000000000', null, 'a0', 45, 50);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0030000-0000-4000-8000-000000000000', null, 'a1', 35, 50);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0030000-0000-4000-8000-000000000000', null, 'a2', null, 50);
select ok(abs(public.course_current_grade('c0030000-0000-4000-8000-000000000000') - 80.000000) < 0.0001, 'parity: no categories = 80.0000');

insert into public.courses (id, user_id, name) values ('c0040000-0000-4000-8000-000000000000', :'uid', 'fixture 4');
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca040000-0000-4000-8000-000000000001', 'c0040000-0000-4000-8000-000000000000', 'A', 1, 0);
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca040000-0000-4000-8000-000000000002', 'c0040000-0000-4000-8000-000000000000', 'B', 3, 1);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0040000-0000-4000-8000-000000000000', 'ca040000-0000-4000-8000-000000000001', 'a0', 100, 100);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0040000-0000-4000-8000-000000000000', 'ca040000-0000-4000-8000-000000000002', 'a1', 60, 100);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0040000-0000-4000-8000-000000000000', 'ca040000-0000-4000-8000-000000000002', 'a2', 10, 100);
select ok(abs(public.course_current_grade('c0040000-0000-4000-8000-000000000000') - 70.000000) < 0.0001, 'parity: weights not totalling 100 = 70.0000');

insert into public.courses (id, user_id, name) values ('c0050000-0000-4000-8000-000000000000', :'uid', 'fixture 5');
insert into public.grade_categories (id, course_id, name, weight, drop_lowest) values ('ca050000-0000-4000-8000-000000000001', 'c0050000-0000-4000-8000-000000000000', 'A', 100, 0);
insert into public.assignments (course_id, category_id, title, points_earned, points_possible) values ('c0050000-0000-4000-8000-000000000000', 'ca050000-0000-4000-8000-000000000001', 'a0', null, 100);
select is(public.course_current_grade('c0050000-0000-4000-8000-000000000000'), null, 'parity: nothing graded = null');

select * from finish();
rollback;
