// Generates src/generated.ts (Material 3 color roles for light and dark, and the course
// palette) and tokens.css from a single seed color, using Google's
// material-color-utilities. Run: pnpm --filter @studypulse/tokens generate
// The output is committed; apps never depend on the color library at runtime.
import { writeFileSync } from "node:fs";

import {
  argbFromHex,
  Hct,
  hexFromArgb,
  MaterialDynamicColors,
  SchemeTonalSpot,
} from "@material/material-color-utilities";

import { buildCss } from "../src/css.ts";
import type { ColorRoles, CourseColor } from "../src/types.ts";

/** Brand seed: a calm, studious blue. Changing it regenerates every role. */
const SEED = "#2F6690";

const ROLES = [
  "primary",
  "onPrimary",
  "primaryContainer",
  "onPrimaryContainer",
  "secondary",
  "onSecondary",
  "secondaryContainer",
  "onSecondaryContainer",
  "tertiary",
  "onTertiary",
  "tertiaryContainer",
  "onTertiaryContainer",
  "error",
  "onError",
  "errorContainer",
  "onErrorContainer",
  "surface",
  "onSurface",
  "surfaceVariant",
  "onSurfaceVariant",
  "surfaceContainerLowest",
  "surfaceContainerLow",
  "surfaceContainer",
  "surfaceContainerHigh",
  "surfaceContainerHighest",
  "outline",
  "outlineVariant",
  "inverseSurface",
  "inverseOnSurface",
  "inversePrimary",
  "scrim",
  "shadow",
] as const satisfies readonly (keyof ColorRoles)[];

function scheme(isDark: boolean): ColorRoles {
  const s = new SchemeTonalSpot(Hct.fromInt(argbFromHex(SEED)), isDark, 0);
  const out = {} as Record<(typeof ROLES)[number], string>;
  for (const role of ROLES) {
    const dynamic = MaterialDynamicColors[role];
    out[role] = hexFromArgb(dynamic.getArgb(s));
  }
  return out;
}

// Course colors: distinct hues, each rendered per theme at fixed HCT tones. Tone gaps of
// 40+ give at least 3:1 and 50+ at least 4.5:1, so every entry passes in both themes;
// src/contrast.test.ts verifies the actual numbers.
const COURSE_HUES: [key: string, label: string, hue: number, chroma: number][] = [
  ["blue", "Blue", 255, 48],
  ["teal", "Teal", 195, 40],
  ["green", "Green", 145, 44],
  ["olive", "Olive", 110, 40],
  ["amber", "Amber", 80, 48],
  ["orange", "Orange", 55, 52],
  ["red", "Red", 25, 56],
  ["pink", "Pink", 350, 48],
  ["purple", "Purple", 305, 44],
  ["indigo", "Indigo", 280, 44],
];

const tone = (hue: number, chroma: number, t: number) =>
  hexFromArgb(Hct.from(hue, chroma, t).toInt());

const coursePalette: CourseColor[] = COURSE_HUES.map(([key, label, hue, chroma]) => ({
  key,
  label,
  // The value stored in courses.color_hex.
  hex: tone(hue, chroma, 45),
  light: {
    stripe: tone(hue, chroma, 45),
    chip: tone(hue, chroma * 0.4, 90),
    onChip: tone(hue, chroma, 10),
  },
  dark: {
    stripe: tone(hue, chroma, 75),
    chip: tone(hue, chroma * 0.6, 30),
    onChip: tone(hue, chroma * 0.4, 92),
  },
}));

const light = scheme(false);
const dark = scheme(true);

const ts = `// GENERATED by scripts/generate.ts from seed ${SEED}. Do not edit; run
// \`pnpm --filter @studypulse/tokens generate\`.
import type { ColorRoles, CourseColor } from "./types.ts";

export const SEED_COLOR = "${SEED}";
export const lightColors: ColorRoles = ${JSON.stringify(light, null, 2)};
export const darkColors: ColorRoles = ${JSON.stringify(dark, null, 2)};
export const coursePalette: readonly CourseColor[] = ${JSON.stringify(coursePalette, null, 2)};
`;
writeFileSync(new URL("../src/generated.ts", import.meta.url), ts);
writeFileSync(new URL("../tokens.css", import.meta.url), buildCss({ light, dark, coursePalette }));
console.log("wrote src/generated.ts and tokens.css");
