// Builds tokens.css: every token as a CSS custom property. Light is the default; dark
// applies with prefers-color-scheme (unless data-theme="light") or data-theme="dark".
import { fontFamily, layout, motion, radii, spacing, typeScale } from "./tokens.ts";
import type { ColorRoles, CourseColor } from "./types.ts";

const kebab = (s: string) => s.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

function colorVars(colors: ColorRoles, palette: readonly CourseColor[], theme: "light" | "dark") {
  // An interface has no index signature, so give Object.entries its value type.
  const entries = Object.entries(colors) as [keyof ColorRoles, string][];
  const lines = entries.map(([k, v]) => `  --sp-color-${kebab(k)}: ${v};`);
  for (const c of palette) {
    const s = c[theme];
    lines.push(
      `  --sp-course-${c.key}-stripe: ${s.stripe};`,
      `  --sp-course-${c.key}-chip: ${s.chip};`,
      `  --sp-course-${c.key}-on-chip: ${s.onChip};`,
    );
  }
  return lines;
}

function staticVars(): string[] {
  const lines = [
    ...Object.entries(spacing).map(([k, v]) => `  --sp-space-${kebab(k)}: ${String(v)}px;`),
    ...Object.entries(radii).map(([k, v]) => `  --sp-radius-${kebab(k)}: ${String(v)}px;`),
    `  --sp-font-sans: ${fontFamily.sans};`,
    `  --sp-font-mono: ${fontFamily.mono};`,
  ];
  for (const [k, t] of Object.entries(typeScale)) {
    const name = kebab(k);
    lines.push(
      `  --sp-type-${name}-size: ${String(t.size / 16)}rem;`,
      `  --sp-type-${name}-line-height: ${String(t.lineHeight / 16)}rem;`,
      `  --sp-type-${name}-weight: ${String(t.weight)};`,
      `  --sp-type-${name}-letter-spacing: ${String(t.letterSpacing)}px;`,
    );
  }
  lines.push(
    `  --sp-layout-sidebar-width: ${String(layout.sidebarWidth)}px;`,
    `  --sp-layout-rail-width: ${String(layout.railWidth)}px;`,
    `  --sp-layout-bottom-bar-height: ${String(layout.bottomBarHeight)}px;`,
    `  --sp-layout-app-bar-height: ${String(layout.appBarHeight)}px;`,
    `  --sp-layout-content-max-width: ${String(layout.contentMaxWidth)}px;`,
    `  --sp-layout-right-panel-width: ${String(layout.rightPanelWidth)}px;`,
    `  --sp-layout-min-target: ${String(layout.minTarget)}px;`,
    `  --sp-layout-target-gap: ${String(layout.targetGap)}px;`,
    `  --sp-layout-course-stripe: ${String(layout.courseStripe)}px;`,
    `  --sp-focus-ring-width: ${String(layout.focusRing.width)}px;`,
    `  --sp-focus-ring-offset: ${String(layout.focusRing.offset)}px;`,
    `  --sp-motion-short: ${String(motion.durationShort)}ms;`,
    `  --sp-motion-medium: ${String(motion.durationMedium)}ms;`,
    `  --sp-motion-easing: ${motion.easing};`,
  );
  return lines;
}

export function buildCss(input: {
  light: ColorRoles;
  dark: ColorRoles;
  coursePalette: readonly CourseColor[];
}): string {
  const dark = colorVars(input.dark, input.coursePalette, "dark").join("\n");
  return [
    "/* GENERATED by packages/tokens/scripts/generate.ts. Do not edit. */",
    "/* Breakpoints (for media queries; CSS variables can't be used there):",
    `   medium ${String(layout.breakpoints.medium)}px, expanded ${String(layout.breakpoints.expanded)}px, wide ${String(layout.breakpoints.wide)}px. */`,
    ":root {",
    "  color-scheme: light;",
    ...staticVars(),
    ...colorVars(input.light, input.coursePalette, "light"),
    "}",
    "@media (prefers-color-scheme: dark) {",
    '  :root:not([data-theme="light"]) {',
    "    color-scheme: dark;",
    dark.replace(/^ {2}/gm, "    "),
    "  }",
    "}",
    ':root[data-theme="dark"] {',
    "  color-scheme: dark;",
    dark,
    "}",
    "",
  ].join("\n");
}
