import { PRIORITY_FIXTURES, PRIORITY_NOW } from "./fixtures.ts";
import { priority } from "./index.ts";

const sqlString = (s: string) => `'${s.replace(/'/g, "''")}'`;

/** The generated pgTAP test asserting SQL task_priority() == TS priority() on every fixture. */
export function renderPriorityParitySql(): string {
  const now = new Date(PRIORITY_NOW);
  const lines = [
    "-- GENERATED by packages/core/scripts/gen-priority-parity.ts from packages/core/src/priority/fixtures.ts.",
    "-- Do not edit; run `pnpm --filter @studypulse/core priority:parity` after changing the formula.",
    "begin;",
    `select plan(${String(PRIORITY_FIXTURES.length)});`,
    "",
  ];
  for (const f of PRIORITY_FIXTURES) {
    const dueAt =
      f.dueInDays === null
        ? null
        : new Date(now.getTime() + f.dueInDays * 86_400_000).toISOString();
    const expected = priority({
      gradeShare: f.gradeShare,
      dueAt,
      now,
      minutesRemaining: f.minutesRemaining,
      status: f.status,
      dailyMinutes: f.dailyMinutes,
    }).score;
    lines.push(
      `select ok(abs(public.task_priority(${String(f.gradeShare)}, ${dueAt ? `${sqlString(dueAt)}::timestamptz` : "null"}, ${sqlString(PRIORITY_NOW)}::timestamptz, ${String(f.minutesRemaining)}, ${sqlString(f.status)}, ${String(f.dailyMinutes)}) - ${expected.toFixed(3)}) < 0.002, ${sqlString(`parity: ${f.name} = ${expected.toFixed(3)}`)});`,
    );
  }
  lines.push("", "select * from finish();", "rollback;", "");
  return lines.join("\n");
}
